### ISSUE TITLE
Missing from JCenter

### ISSUE THREAD

**Issue by nickbabcock** [arteam/dropwizard-http2-client#1]
Looks like it hasn't been uploaded: http://jcenter.bintray.com/com/github/arteam/

Getting the following error:

> Failure to find com.github.arteam:dropwizard-http2-client:jar:0.1 in https://jcenter.bintray.com

**Comment by arteam** [comment]
Thanks for reporting this. I actually forgot to sync my Bintray repository with JCenter and did it only today's morning. Waiting for an approval from the JFrog guys. For the time being you can use:
```xml
<repository>
  <id>bintray-arteam-maven</id>
  <name>bintray</name>
  <url>http://dl.bintray.com/arteam/maven</url>
</repository>
```

**Comment by nickbabcock** [comment]
No problem, also running into little compilation issue

```java
final org.eclipse.jetty.client.HttpClient client = null;
```

Gives the error:
> package org.eclipse.jetty.client does not exist

Adding the following dependency to pom fixes it.

```xml
<dependency>
    <groupId>org.eclipse.jetty</groupId>
    <artifactId>jetty-client</artifactId>
</dependency>
```

Not sure if this is WAD, or not.

**Comment by arteam** [comment]
Hmm, that sound strange. The dependency is already declared in the [POM](https://github.com/arteam/dropwizard-http2-client/blob/master/pom.xml#L91), so it should be pulled transitively.

**Comment by arteam** [comment]
I wonder if it's caused by `dropwizard-bom` which declares `jetty-client` and `http2-http-client-transport` with the test scope. Let me check.

**Comment by arteam** [comment]
Actually, we need to fix it in Dropwizard :) Those dependencies are declared with the test scope, but they should not be, because some users want to use them as compile dependencies . Because of that they are forced to specify:
```
  <dependency>
            <groupId>org.eclipse.jetty</groupId>
            <artifactId>jetty-client</artifactId>
            <scope>compile</scope>
        </dependency>

        <dependency>
            <groupId>org.eclipse.jetty.http2</groupId>
            <artifactId>http2-http-client-transport</artifactId>
            <scope>compile</scope>
        </dependency>
```
or don't use `dropwizard-bom`.

**Comment by arteam** [comment]
I've added this information to the README file.

**Comment by arteam** [comment]
The artefact has been published to [JCenter](http://jcenter.bintray.com/com/github/arteam/dropwizard-http2-client/).
